# Silver quality és feltöltés

Ez a notebook a bronze OHLCV és silver/calendar adatokból előállítja a silver generated OHLCV táblát.

A folyamat:

1. Betölti a bronze és calendar adatokat Azure-ból.
2. Calendar alapján szűri az elvárt gyertyahelyeket.
3. Generált OHLC gyertyát készít.
4. Quality mezőket ad hozzá:
   - `consensus_quality`
   - `candle_quality`
   - `is_outlier`
   - `quality_status`
5. Broker ranking táblát készít.
6. Feltölti a silver adatokat Azure-ba havi és asset bontásban.

Két generálási módszer van:

- `method=0`: medián alapú OHLC
- `method=1`: automatikus preferred broker alapú OHLC

A két módszer külön Azure útvonalra kerül:

- `silver/generated_ohlcv/method_0/...`
- `silver/generated_ohlcv/method_1/...`

In [7]:
START_MONTH = "2024-01"
END_MONTH = "2025-12"
BROKERS = None
ASSETS = None
INTERVAL = "1m"

In [8]:
import importlib

import quality.data_loader
import quality.calendar_alignment
import quality.candle_generation

importlib.reload(quality.data_loader)
importlib.reload(quality.calendar_alignment)
importlib.reload(quality.candle_generation)

from quality.data_loader import load_bronze_ohlcv
from quality.calendar_alignment import load_calendar
from quality.candle_generation import build_broker_wide_table


bronze_df = load_bronze_ohlcv(
    start_month=START_MONTH,
    end_month=END_MONTH,
    brokers=BROKERS,
    assets=ASSETS,
    interval=INTERVAL,
    source="azure",
    print_progress=True,
)

calendar_df = load_calendar(
    start_month=START_MONTH,
    end_month=END_MONTH,
    assets=ASSETS,
    interval=INTERVAL,
    source="azure",
    print_progress=True,
)

quality_wide_df = build_broker_wide_table(
    bronze_df=bronze_df,
    calendar_df=calendar_df,
)

quality_wide_df.shape

reading bronze/binance/btcusd/2024/01/BTCUSDT-1m-2024-01.parquet
reading bronze/binance/btcusd/2024/02/BTCUSDT-1m-2024-02.parquet
reading bronze/binance/btcusd/2024/03/BTCUSDT-1m-2024-03.parquet
reading bronze/binance/btcusd/2024/04/BTCUSDT-1m-2024-04.parquet
reading bronze/binance/btcusd/2024/05/BTCUSDT-1m-2024-05.parquet
reading bronze/binance/btcusd/2024/06/BTCUSDT-1m-2024-06.parquet
reading bronze/binance/btcusd/2024/07/BTCUSDT-1m-2024-07.parquet
reading bronze/binance/btcusd/2024/08/BTCUSDT-1m-2024-08.parquet
reading bronze/binance/btcusd/2024/09/BTCUSDT-1m-2024-09.parquet
reading bronze/binance/btcusd/2024/10/BTCUSDT-1m-2024-10.parquet
reading bronze/binance/btcusd/2024/11/BTCUSDT-1m-2024-11.parquet
reading bronze/binance/btcusd/2024/12/BTCUSDT-1m-2024-12.parquet
reading bronze/binance/btcusd/2025/01/BTCUSDT-1m-2025-01.parquet
reading bronze/binance/btcusd/2025/02/BTCUSDT-1m-2025-02.parquet
reading bronze/binance/btcusd/2025/03/BTCUSDT-1m-2025-03.parquet
reading bronze/binance/btcusd/2025/04/BTCUSDT-1m-2025-04.parquet
reading bronze/binance/btcusd/2025/05/BTCUSDT-1m-2025-05.parquet
reading bronze/binance/btcusd/2025/06/BTCUSDT-1m-2025-06.parquet
reading bronze/binance/btcusd/2025/07/BTCUSDT-1m-2025-07.parquet
reading bronze/binance/btcusd/2025/08/BTCUSDT-1m-2025-08.parquet
reading bronze/binance/btcusd/2025/09/BTCUSDT-1m-2025-09.parquet
reading bronze/binance/btcusd/2025/10/BTCUSDT-1m-2025-10.parquet
reading bronze/binance/btcusd/2025/11/BTCUSDT-1m-2025-11.parquet
reading bronze/binance/btcusd/2025/12/BTCUSDT-1m-2025-12.parquet
reading bronze/dukascopy/btcusd/2024/01/BTCUSD-1m-2024-01.parquet
reading bronze/dukascopy/btcusd/2024/02/BTCUSD-1m-2024-02.parquet
reading bronze/dukascopy/btcusd/2024/03/BTCUSD-1m-2024-03.parquet
reading bronze/dukascopy/btcusd/2024/04/BTCUSD-1m-2024-04.parquet
reading bronze/dukascopy/btcusd/2024/05/BTCUSD-1m-2024-05.parquet
reading bronze/dukascopy/btcusd/2024/06/BTCUSD-1m-2024-06.parquet
reading bronze/dukascopy/btcusd/2024/07/BTCUSD-1m-2024-07.parquet
reading bronze/dukascopy/btcusd/2024/08/BTCUSD-1m-2024-08.parquet
reading bronze/dukascopy/btcusd/2024/09/BTCUSD-1m-2024-09.parquet
reading bronze/dukascopy/btcusd/2024/10/BTCUSD-1m-2024-10.parquet
reading bronze/dukascopy/btcusd/2024/11/BTCUSD-1m-2024-11.parquet
reading bronze/dukascopy/btcusd/2024/12/BTCUSD-1m-2024-12.parquet
reading bronze/dukascopy/btcusd/2025/01/BTCUSD-1m-2025-01.parquet
reading bronze/dukascopy/btcusd/2025/02/BTCUSD-1m-2025-02.parquet
reading bronze/dukascopy/btcusd/2025/03/BTCUSD-1m-2025-03.parquet
reading bronze/dukascopy/btcusd/2025/04/BTCUSD-1m-2025-04.parquet
reading bronze/dukascopy/btcusd/2025/05/BTCUSD-1m-2025-05.parquet
reading bronze/dukascopy/btcusd/2025/06/BTCUSD-1m-2025-06.parquet
reading bronze/dukascopy/btcusd/2025/07/BTCUSD-1m-2025-07.parquet
reading bronze/dukascopy/btcusd/2025/08/BTCUSD-1m-2025-08.parquet
reading bronze/dukascopy/btcusd/2025/09/BTCUSD-1m-2025-09.parquet
reading bronze/dukascopy/btcusd/2025/10/BTCUSD-1m-2025-10.parquet
reading bronze/dukascopy/btcusd/2025/11/BTCUSD-1m-2025-11.parquet
reading bronze/dukascopy/btcusd/2025/12/BTCUSD-1m-2025-12.parquet
reading bronze/dukascopy/dax/2024/01/DEUIDXEUR-1m-2024-01.parquet
reading bronze/dukascopy/dax/2024/02/DEUIDXEUR-1m-2024-02.parquet
reading bronze/dukascopy/dax/2024/03/DEUIDXEUR-1m-2024-03.parquet
reading bronze/dukascopy/dax/2024/04/DEUIDXEUR-1m-2024-04.parquet
reading bronze/dukascopy/dax/2024/05/DEUIDXEUR-1m-2024-05.parquet
reading bronze/dukascopy/dax/2024/06/DEUIDXEUR-1m-2024-06.parquet
reading bronze/dukascopy/dax/2024/07/DEUIDXEUR-1m-2024-07.parquet
reading bronze/dukascopy/dax/2024/08/DEUIDXEUR-1m-2024-08.parquet
reading bronze/dukascopy/dax/2024/09/DEUIDXEUR-1m-2024-09.parquet
reading bronze/dukascopy/dax/2024/10/DEUIDXEUR-1m-2024-10.parquet
reading bronze/dukascopy/dax/2024/11/DEUIDXEUR-1m-2024-11.parquet
reading bronze/dukascopy/dax/2024/12/DEUIDXEUR-1m-2024-12.parquet
reading bronze/dukascopy/dax/2025/01/DEUIDXEUR-1m-2025-01.parquet
reading bronze/dukascopy/dax/2025/02/DEUIDXEUR-1m-2025-02.parquet
reading bronze/dukascopy/dax/2025/03/DEUIDXEUR-1m-2025-03.parquet
reading bronze/dukascopy/dax/2025/04/DEUIDXEUR-1m-2025-04.parquet
reading bronze/dukascopy/dax/2025/05/DEUIDXEUR-1m-2025-05.parquet
reading bronze/dukascopy/dax/2025/06/DEUIDXEUR-1m-2025-06.parquet
reading bronze/dukascopy/dax/2025/07/DEUIDXEUR-1m-2025-07.parquet
reading bronze/dukascopy/dax/2025/08/DEUIDXEUR-1m-2025-08.parquet
reading bronze/dukascopy/dax/2025/09/DEUIDXEUR-1m-2025-09.parquet
reading bronze/dukascopy/dax/2025/10/DEUIDXEUR-1m-2025-10.parquet
reading bronze/dukascopy/dax/2025/11/DEUIDXEUR-1m-2025-11.parquet
reading bronze/dukascopy/dax/2025/12/DEUIDXEUR-1m-2025-12.parquet
reading bronze/dukascopy/eurusd/2024/01/EURUSD-1m-2024-01.parquet
reading bronze/dukascopy/eurusd/2024/02/EURUSD-1m-2024-02.parquet
reading bronze/dukascopy/eurusd/2024/03/EURUSD-1m-2024-03.parquet
reading bronze/dukascopy/eurusd/2024/04/EURUSD-1m-2024-04.parquet
reading bronze/dukascopy/eurusd/2024/05/EURUSD-1m-2024-05.parquet
reading bronze/dukascopy/eurusd/2024/06/EURUSD-1m-2024-06.parquet
reading bronze/dukascopy/eurusd/2024/07/EURUSD-1m-2024-07.parquet
reading bronze/dukascopy/eurusd/2024/08/EURUSD-1m-2024-08.parquet
reading bronze/dukascopy/eurusd/2024/09/EURUSD-1m-2024-09.parquet
reading bronze/dukascopy/eurusd/2024/10/EURUSD-1m-2024-10.parquet
reading bronze/dukascopy/eurusd/2024/11/EURUSD-1m-2024-11.parquet
reading bronze/dukascopy/eurusd/2024/12/EURUSD-1m-2024-12.parquet
reading bronze/dukascopy/eurusd/2025/01/EURUSD-1m-2025-01.parquet
reading bronze/dukascopy/eurusd/2025/02/EURUSD-1m-2025-02.parquet
reading bronze/dukascopy/eurusd/2025/03/EURUSD-1m-2025-03.parquet
reading bronze/dukascopy/eurusd/2025/04/EURUSD-1m-2025-04.parquet
reading bronze/dukascopy/eurusd/2025/05/EURUSD-1m-2025-05.parquet
reading bronze/dukascopy/eurusd/2025/06/EURUSD-1m-2025-06.parquet
reading bronze/dukascopy/eurusd/2025/07/EURUSD-1m-2025-07.parquet
reading bronze/dukascopy/eurusd/2025/08/EURUSD-1m-2025-08.parquet
reading bronze/dukascopy/eurusd/2025/09/EURUSD-1m-2025-09.parquet
reading bronze/dukascopy/eurusd/2025/10/EURUSD-1m-2025-10.parquet
reading bronze/dukascopy/eurusd/2025/11/EURUSD-1m-2025-11.parquet
reading bronze/dukascopy/eurusd/2025/12/EURUSD-1m-2025-12.parquet
reading bronze/dukascopy/us500/2024/01/USA500IDXUSD-1m-2024-01.parquet
reading bronze/dukascopy/us500/2024/02/USA500IDXUSD-1m-2024-02.parquet
reading bronze/dukascopy/us500/2024/03/USA500IDXUSD-1m-2024-03.parquet
reading bronze/dukascopy/us500/2024/04/USA500IDXUSD-1m-2024-04.parquet
reading bronze/dukascopy/us500/2024/05/USA500IDXUSD-1m-2024-05.parquet
reading bronze/dukascopy/us500/2024/06/USA500IDXUSD-1m-2024-06.parquet
reading bronze/dukascopy/us500/2024/07/USA500IDXUSD-1m-2024-07.parquet
reading bronze/dukascopy/us500/2024/08/USA500IDXUSD-1m-2024-08.parquet
reading bronze/dukascopy/us500/2024/09/USA500IDXUSD-1m-2024-09.parquet
reading bronze/dukascopy/us500/2024/10/USA500IDXUSD-1m-2024-10.parquet
reading bronze/dukascopy/us500/2024/11/USA500IDXUSD-1m-2024-11.parquet
reading bronze/dukascopy/us500/2024/12/USA500IDXUSD-1m-2024-12.parquet
reading bronze/dukascopy/us500/2025/01/USA500IDXUSD-1m-2025-01.parquet
reading bronze/dukascopy/us500/2025/02/USA500IDXUSD-1m-2025-02.parquet
reading bronze/dukascopy/us500/2025/03/USA500IDXUSD-1m-2025-03.parquet
reading bronze/dukascopy/us500/2025/04/USA500IDXUSD-1m-2025-04.parquet
reading bronze/dukascopy/us500/2025/05/USA500IDXUSD-1m-2025-05.parquet
reading bronze/dukascopy/us500/2025/06/USA500IDXUSD-1m-2025-06.parquet
reading bronze/dukascopy/us500/2025/07/USA500IDXUSD-1m-2025-07.parquet
reading bronze/dukascopy/us500/2025/08/USA500IDXUSD-1m-2025-08.parquet
reading bronze/dukascopy/us500/2025/09/USA500IDXUSD-1m-2025-09.parquet
reading bronze/dukascopy/us500/2025/10/USA500IDXUSD-1m-2025-10.parquet
reading bronze/dukascopy/us500/2025/11/USA500IDXUSD-1m-2025-11.parquet
reading bronze/dukascopy/us500/2025/12/USA500IDXUSD-1m-2025-12.parquet
reading bronze/dukascopy/xagusd/2024/01/XAGUSD-1m-2024-01.parquet
reading bronze/dukascopy/xagusd/2024/02/XAGUSD-1m-2024-02.parquet
reading bronze/dukascopy/xagusd/2024/03/XAGUSD-1m-2024-03.parquet
reading bronze/dukascopy/xagusd/2024/04/XAGUSD-1m-2024-04.parquet
reading bronze/dukascopy/xagusd/2024/05/XAGUSD-1m-2024-05.parquet
reading bronze/dukascopy/xagusd/2024/06/XAGUSD-1m-2024-06.parquet
reading bronze/dukascopy/xagusd/2024/07/XAGUSD-1m-2024-07.parquet
reading bronze/dukascopy/xagusd/2024/08/XAGUSD-1m-2024-08.parquet
reading bronze/dukascopy/xagusd/2024/09/XAGUSD-1m-2024-09.parquet
reading bronze/dukascopy/xagusd/2024/10/XAGUSD-1m-2024-10.parquet
reading bronze/dukascopy/xagusd/2024/11/XAGUSD-1m-2024-11.parquet
reading bronze/dukascopy/xagusd/2024/12/XAGUSD-1m-2024-12.parquet
reading bronze/dukascopy/xagusd/2025/01/XAGUSD-1m-2025-01.parquet
reading bronze/dukascopy/xagusd/2025/02/XAGUSD-1m-2025-02.parquet
reading bronze/dukascopy/xagusd/2025/03/XAGUSD-1m-2025-03.parquet
reading bronze/dukascopy/xagusd/2025/04/XAGUSD-1m-2025-04.parquet
reading bronze/dukascopy/xagusd/2025/05/XAGUSD-1m-2025-05.parquet
reading bronze/dukascopy/xagusd/2025/06/XAGUSD-1m-2025-06.parquet
reading bronze/dukascopy/xagusd/2025/07/XAGUSD-1m-2025-07.parquet
reading bronze/dukascopy/xagusd/2025/08/XAGUSD-1m-2025-08.parquet
reading bronze/dukascopy/xagusd/2025/09/XAGUSD-1m-2025-09.parquet
reading bronze/dukascopy/xagusd/2025/10/XAGUSD-1m-2025-10.parquet
reading bronze/dukascopy/xagusd/2025/11/XAGUSD-1m-2025-11.parquet
reading bronze/dukascopy/xagusd/2025/12/XAGUSD-1m-2025-12.parquet
reading bronze/dukascopy/xauusd/2024/01/XAUUSD-1m-2024-01.parquet
reading bronze/dukascopy/xauusd/2024/02/XAUUSD-1m-2024-02.parquet
reading bronze/dukascopy/xauusd/2024/03/XAUUSD-1m-2024-03.parquet
reading bronze/dukascopy/xauusd/2024/04/XAUUSD-1m-2024-04.parquet
reading bronze/dukascopy/xauusd/2024/05/XAUUSD-1m-2024-05.parquet
reading bronze/dukascopy/xauusd/2024/06/XAUUSD-1m-2024-06.parquet
reading bronze/dukascopy/xauusd/2024/07/XAUUSD-1m-2024-07.parquet
reading bronze/dukascopy/xauusd/2024/08/XAUUSD-1m-2024-08.parquet
reading bronze/dukascopy/xauusd/2024/09/XAUUSD-1m-2024-09.parquet
reading bronze/dukascopy/xauusd/2024/10/XAUUSD-1m-2024-10.parquet
reading bronze/dukascopy/xauusd/2024/11/XAUUSD-1m-2024-11.parquet
reading bronze/dukascopy/xauusd/2024/12/XAUUSD-1m-2024-12.parquet
reading bronze/dukascopy/xauusd/2025/01/XAUUSD-1m-2025-01.parquet
reading bronze/dukascopy/xauusd/2025/02/XAUUSD-1m-2025-02.parquet
reading bronze/dukascopy/xauusd/2025/03/XAUUSD-1m-2025-03.parquet
reading bronze/dukascopy/xauusd/2025/04/XAUUSD-1m-2025-04.parquet
reading bronze/dukascopy/xauusd/2025/05/XAUUSD-1m-2025-05.parquet
reading bronze/dukascopy/xauusd/2025/06/XAUUSD-1m-2025-06.parquet
reading bronze/dukascopy/xauusd/2025/07/XAUUSD-1m-2025-07.parquet
reading bronze/dukascopy/xauusd/2025/08/XAUUSD-1m-2025-08.parquet
reading bronze/dukascopy/xauusd/2025/09/XAUUSD-1m-2025-09.parquet
reading bronze/dukascopy/xauusd/2025/10/XAUUSD-1m-2025-10.parquet
reading bronze/dukascopy/xauusd/2025/11/XAUUSD-1m-2025-11.parquet
reading bronze/dukascopy/xauusd/2025/12/XAUUSD-1m-2025-12.parquet
reading bronze/interactive_brokers/dax/2024/01/DAX-1m-2024-01.parquet
reading bronze/interactive_brokers/dax/2024/02/DAX-1m-2024-02.parquet
reading bronze/interactive_brokers/dax/2024/03/DAX-1m-2024-03.parquet
reading bronze/interactive_brokers/dax/2024/04/DAX-1m-2024-04.parquet
reading bronze/interactive_brokers/dax/2024/05/DAX-1m-2024-05.parquet
reading bronze/interactive_brokers/dax/2024/06/DAX-1m-2024-06.parquet
reading bronze/interactive_brokers/dax/2024/07/DAX-1m-2024-07.parquet
reading bronze/interactive_brokers/dax/2024/08/DAX-1m-2024-08.parquet
reading bronze/interactive_brokers/dax/2024/09/DAX-1m-2024-09.parquet
reading bronze/interactive_brokers/dax/2024/10/DAX-1m-2024-10.parquet
reading bronze/interactive_brokers/dax/2024/11/DAX-1m-2024-11.parquet
reading bronze/interactive_brokers/dax/2024/12/DAX-1m-2024-12.parquet
reading bronze/interactive_brokers/dax/2025/01/DAX-1m-2025-01.parquet
reading bronze/interactive_brokers/dax/2025/02/DAX-1m-2025-02.parquet
reading bronze/interactive_brokers/dax/2025/03/DAX-1m-2025-03.parquet
reading bronze/interactive_brokers/dax/2025/04/DAX-1m-2025-04.parquet
reading bronze/interactive_brokers/dax/2025/05/DAX-1m-2025-05.parquet
reading bronze/interactive_brokers/dax/2025/06/DAX-1m-2025-06.parquet
reading bronze/interactive_brokers/dax/2025/07/DAX-1m-2025-07.parquet
reading bronze/interactive_brokers/dax/2025/08/DAX-1m-2025-08.parquet
reading bronze/interactive_brokers/dax/2025/09/DAX-1m-2025-09.parquet
reading bronze/interactive_brokers/dax/2025/10/DAX-1m-2025-10.parquet
reading bronze/interactive_brokers/dax/2025/11/DAX-1m-2025-11.parquet
reading bronze/interactive_brokers/dax/2025/12/DAX-1m-2025-12.parquet
reading bronze/interactive_brokers/eurusd/2024/01/EURUSD-1m-2024-01.parquet
reading bronze/interactive_brokers/eurusd/2024/02/EURUSD-1m-2024-02.parquet
reading bronze/interactive_brokers/eurusd/2024/03/EURUSD-1m-2024-03.parquet
reading bronze/interactive_brokers/eurusd/2024/04/EURUSD-1m-2024-04.parquet
reading bronze/interactive_brokers/eurusd/2024/05/EURUSD-1m-2024-05.parquet
reading bronze/interactive_brokers/eurusd/2024/06/EURUSD-1m-2024-06.parquet
reading bronze/interactive_brokers/eurusd/2024/07/EURUSD-1m-2024-07.parquet
reading bronze/interactive_brokers/eurusd/2024/08/EURUSD-1m-2024-08.parquet
reading bronze/interactive_brokers/eurusd/2024/09/EURUSD-1m-2024-09.parquet
reading bronze/interactive_brokers/eurusd/2024/10/EURUSD-1m-2024-10.parquet
reading bronze/interactive_brokers/eurusd/2024/11/EURUSD-1m-2024-11.parquet
reading bronze/interactive_brokers/eurusd/2024/12/EURUSD-1m-2024-12.parquet
reading bronze/interactive_brokers/eurusd/2025/01/EURUSD-1m-2025-01.parquet
reading bronze/interactive_brokers/eurusd/2025/02/EURUSD-1m-2025-02.parquet
reading bronze/interactive_brokers/eurusd/2025/03/EURUSD-1m-2025-03.parquet
reading bronze/interactive_brokers/eurusd/2025/04/EURUSD-1m-2025-04.parquet
reading bronze/interactive_brokers/eurusd/2025/05/EURUSD-1m-2025-05.parquet
reading bronze/interactive_brokers/eurusd/2025/06/EURUSD-1m-2025-06.parquet
reading bronze/interactive_brokers/eurusd/2025/07/EURUSD-1m-2025-07.parquet
reading bronze/interactive_brokers/eurusd/2025/08/EURUSD-1m-2025-08.parquet
reading bronze/interactive_brokers/eurusd/2025/09/EURUSD-1m-2025-09.parquet
reading bronze/interactive_brokers/eurusd/2025/10/EURUSD-1m-2025-10.parquet
reading bronze/interactive_brokers/eurusd/2025/11/EURUSD-1m-2025-11.parquet
reading bronze/interactive_brokers/eurusd/2025/12/EURUSD-1m-2025-12.parquet
reading bronze/interactive_brokers/us500/2024/01/US500-1m-2024-01.parquet
reading bronze/interactive_brokers/us500/2024/02/US500-1m-2024-02.parquet
reading bronze/interactive_brokers/us500/2024/03/US500-1m-2024-03.parquet
reading bronze/interactive_brokers/us500/2024/04/US500-1m-2024-04.parquet
reading bronze/interactive_brokers/us500/2024/05/US500-1m-2024-05.parquet
reading bronze/interactive_brokers/us500/2024/06/US500-1m-2024-06.parquet
reading bronze/interactive_brokers/us500/2024/07/US500-1m-2024-07.parquet
reading bronze/interactive_brokers/us500/2024/08/US500-1m-2024-08.parquet
reading bronze/interactive_brokers/us500/2024/09/US500-1m-2024-09.parquet
reading bronze/interactive_brokers/us500/2024/10/US500-1m-2024-10.parquet
reading bronze/interactive_brokers/us500/2024/11/US500-1m-2024-11.parquet
reading bronze/interactive_brokers/us500/2024/12/US500-1m-2024-12.parquet
reading bronze/interactive_brokers/us500/2025/01/US500-1m-2025-01.parquet
reading bronze/interactive_brokers/us500/2025/02/US500-1m-2025-02.parquet
reading bronze/interactive_brokers/us500/2025/03/US500-1m-2025-03.parquet
reading bronze/interactive_brokers/us500/2025/04/US500-1m-2025-04.parquet
reading bronze/interactive_brokers/us500/2025/05/US500-1m-2025-05.parquet
reading bronze/interactive_brokers/us500/2025/06/US500-1m-2025-06.parquet
reading bronze/interactive_brokers/us500/2025/07/US500-1m-2025-07.parquet
reading bronze/interactive_brokers/us500/2025/08/US500-1m-2025-08.parquet
reading bronze/interactive_brokers/us500/2025/09/US500-1m-2025-09.parquet
reading bronze/interactive_brokers/us500/2025/10/US500-1m-2025-10.parquet
reading bronze/interactive_brokers/us500/2025/11/US500-1m-2025-11.parquet
reading bronze/interactive_brokers/us500/2025/12/US500-1m-2025-12.parquet
reading bronze/interactive_brokers/xagusd/2024/01/XAGUSD-1m-2024-01.parquet
reading bronze/interactive_brokers/xagusd/2024/02/XAGUSD-1m-2024-02.parquet
reading bronze/interactive_brokers/xagusd/2024/03/XAGUSD-1m-2024-03.parquet
reading bronze/interactive_brokers/xagusd/2024/04/XAGUSD-1m-2024-04.parquet
reading bronze/interactive_brokers/xagusd/2024/05/XAGUSD-1m-2024-05.parquet
reading bronze/interactive_brokers/xagusd/2024/06/XAGUSD-1m-2024-06.parquet
reading bronze/interactive_brokers/xagusd/2024/07/XAGUSD-1m-2024-07.parquet
reading bronze/interactive_brokers/xagusd/2024/08/XAGUSD-1m-2024-08.parquet
reading bronze/interactive_brokers/xagusd/2024/09/XAGUSD-1m-2024-09.parquet
reading bronze/interactive_brokers/xagusd/2024/10/XAGUSD-1m-2024-10.parquet
reading bronze/interactive_brokers/xagusd/2024/11/XAGUSD-1m-2024-11.parquet
reading bronze/interactive_brokers/xagusd/2024/12/XAGUSD-1m-2024-12.parquet
reading bronze/interactive_brokers/xagusd/2025/01/XAGUSD-1m-2025-01.parquet
reading bronze/interactive_brokers/xagusd/2025/02/XAGUSD-1m-2025-02.parquet
reading bronze/interactive_brokers/xagusd/2025/03/XAGUSD-1m-2025-03.parquet
reading bronze/interactive_brokers/xagusd/2025/04/XAGUSD-1m-2025-04.parquet
reading bronze/interactive_brokers/xagusd/2025/05/XAGUSD-1m-2025-05.parquet
reading bronze/interactive_brokers/xagusd/2025/06/XAGUSD-1m-2025-06.parquet
reading bronze/interactive_brokers/xagusd/2025/07/XAGUSD-1m-2025-07.parquet
reading bronze/interactive_brokers/xagusd/2025/08/XAGUSD-1m-2025-08.parquet
reading bronze/interactive_brokers/xagusd/2025/09/XAGUSD-1m-2025-09.parquet
reading bronze/interactive_brokers/xagusd/2025/10/XAGUSD-1m-2025-10.parquet
reading bronze/interactive_brokers/xagusd/2025/11/XAGUSD-1m-2025-11.parquet
reading bronze/interactive_brokers/xagusd/2025/12/XAGUSD-1m-2025-12.parquet
reading bronze/interactive_brokers/xauusd/2024/01/XAUUSD-1m-2024-01.parquet
reading bronze/interactive_brokers/xauusd/2024/02/XAUUSD-1m-2024-02.parquet
reading bronze/interactive_brokers/xauusd/2024/03/XAUUSD-1m-2024-03.parquet
reading bronze/interactive_brokers/xauusd/2024/04/XAUUSD-1m-2024-04.parquet
reading bronze/interactive_brokers/xauusd/2024/05/XAUUSD-1m-2024-05.parquet
reading bronze/interactive_brokers/xauusd/2024/06/XAUUSD-1m-2024-06.parquet
reading bronze/interactive_brokers/xauusd/2024/07/XAUUSD-1m-2024-07.parquet
reading bronze/interactive_brokers/xauusd/2024/08/XAUUSD-1m-2024-08.parquet
reading bronze/interactive_brokers/xauusd/2024/09/XAUUSD-1m-2024-09.parquet
reading bronze/interactive_brokers/xauusd/2024/10/XAUUSD-1m-2024-10.parquet
reading bronze/interactive_brokers/xauusd/2024/11/XAUUSD-1m-2024-11.parquet
reading bronze/interactive_brokers/xauusd/2024/12/XAUUSD-1m-2024-12.parquet
reading bronze/interactive_brokers/xauusd/2025/01/XAUUSD-1m-2025-01.parquet
reading bronze/interactive_brokers/xauusd/2025/02/XAUUSD-1m-2025-02.parquet
reading bronze/interactive_brokers/xauusd/2025/03/XAUUSD-1m-2025-03.parquet
reading bronze/interactive_brokers/xauusd/2025/04/XAUUSD-1m-2025-04.parquet
reading bronze/interactive_brokers/xauusd/2025/05/XAUUSD-1m-2025-05.parquet
reading bronze/interactive_brokers/xauusd/2025/06/XAUUSD-1m-2025-06.parquet
reading bronze/interactive_brokers/xauusd/2025/07/XAUUSD-1m-2025-07.parquet
reading bronze/interactive_brokers/xauusd/2025/08/XAUUSD-1m-2025-08.parquet
reading bronze/interactive_brokers/xauusd/2025/09/XAUUSD-1m-2025-09.parquet
reading bronze/interactive_brokers/xauusd/2025/10/XAUUSD-1m-2025-10.parquet

(4191720, 36)

In [9]:
import quality.silver_ohlcv

importlib.reload(quality.silver_ohlcv)
importlib.reload(quality.candle_generation)

from quality.candle_generation import generate_candles_from_brokers
from quality.silver_ohlcv import (
    build_silver_ohlcv_from_generated,
    build_silver_ohlcv_summary,
)


method_0_generated_df = generate_candles_from_brokers(
    quality_wide_df,
    method=0,
)

method_0_silver_ohlcv_df = build_silver_ohlcv_from_generated(
    method_0_generated_df,
)

method_0_summary_df = build_silver_ohlcv_summary(
    method_0_silver_ohlcv_df,
)

method_0_summary_df

,asset,consensus_quality,candle_quality,is_outlier,quality_status,rows,generated_rows,start,end,avg_broker_count,max_close_diff_pct,max_abs_return_pct
0,BTCUSD,multi_source,bad,False,bad,230,230,2024-01-05 01:47:00+00:00,2025-10-10 23:16:00+00:00,2.000000,3.365631,1.795249
1,BTCUSD,multi_source,bad,True,bad,4,4,2024-01-05 01:48:00+00:00,2025-10-10 21:21:00+00:00,2.000000,5.355351,2.588428
2,BTCUSD,multi_source,good,False,good,981420,981420,2024-01-01 21:12:00+00:00,2025-12-31 14:58:00+00:00,2.000000,0.100000,1.861671
3,BTCUSD,multi_source,good,True,bad,5,5,2024-01-03 12:01:00+00:00,2025-01-23 20:12:00+00:00,2.000000,0.076114,2.885488
4,BTCUSD,multi_source,warning,False,warning,60188,60188,2024-01-02 00:15:00+00:00,2025-12-31 14:54:00+00:00,2.000000,0.299918,1.949372
5,BTCUSD,multi_source,warning,True,bad,3,3,2024-08-05 01:10:00+00:00,2024-12-05 22:28:00+00:00,2.000000,0.202889,3.672727
6,BTCUSD,single_source,warning,False,warning,10790,10790,2024-01-01 00:00:00+00:00,2025-12-31 23:59:00+00:00,1.000000,0.000000,1.303564
7,DAX,missing,missing,False,missing,21,0,2024-01-24 08:00:00+00:00,2025-10-02 07:01:00+00:00,NaN,NaN,NaN
8,DAX,multi_source,bad,False,bad,469,469,2024-03-21 08:00:00+00:00,2025-12-30 16:39:00+00:00,2.000000,2.614862,0.667693
9,DAX,multi_source,bad,True,bad,10,10,2024-04-05 07:00:00+00:00,2025-04-09 11:00:00+00:00,2.000000,1.804817,1.432111
10,DAX,multi_source,good,False,good,255398,255398,2024-01-02 08:02:00+00:00,2025-12-30 13:48:00+00:00,2.000000,0.049979,0.727934
11,DAX,multi_source,good,True,bad,7,7,2025-04-07 14:10:00+00:00,2025-06-27 07:00:00+00:00,2.000000,0.033537,1.356945
12,DAX,multi_source,warning,False,warning,2999,2999,2024-01-02 09:30:00+00:00,2025-12-30 14:47:00+00:00,2.000000,0.199071,0.733346
13,DAX,multi_source,warning,True,bad,4,4,2024-04-12 07:00:00+00:00,2025-04-09 11:02:00+00:00,2.000000,0.165784,0.960379
14,DAX,single_source,warning,False,warning,4675,4675,2024-01-02 08:00:00+00:00,2025-12-29 08:01:00+00:00,1.000000,0.000000,0.749947
15,DAX,single_source,warning,True,bad,57,57,2024-01-17 08:00:00+00:00,2025-11-21 08:00:00+00:00,1.000000,0.000000,8.214418
16,EURUSD,missing,missing,False,missing,18638,0,2024-01-01 19:00:00+00:00,2025-12-30 22:03:00+00:00,NaN,NaN,NaN
17,EURUSD,multi_source,bad,False,bad,3,3,2025-04-20 21:51:00+00:00,2025-04-20 21:59:00+00:00,2.000000,0.124046,0.040504
18,EURUSD,multi_source,good,False,good,706081,706081,2024-01-01 22:00:00+00:00,2025-12-31 16:59:00+00:00,2.925188,0.019979,0.199070
19,EURUSD,multi_source,good,True,bad,77,77,2024-01-05 13:30:00+00:00,2025-10-24 12:30:00+00:00,2.922078,0.016411,0.567143
20,EURUSD,multi_source,warning,False,warning,595,595,2024-01-05 13:39:00+00:00,2025-12-28 22:20:00+00:00,2.557983,0.080412,0.172539
21,EURUSD,multi_source,warning,True,bad,10,10,2025-01-20 13:30:00+00:00,2025-10-29 18:35:00+00:00,3.000000,0.068605,0.719638
22,EURUSD,single_source,warning,False,warning,13583,13583,2024-01-01 19:01:00+00:00,2025-12-30 22:14:00+00:00,1.000000,0.000000,0.198483
23,EURUSD,single_source,warning,True,bad,3,3,2025-02-02 19:24:00+00:00,2025-02-02 19:29:00+00:00,1.000000,0.000000,0.364183
24,US500,missing,missing,False,missing,3218,0,2024-02-01 00:59:00+00:00,2025-12-31 23:59:00+00:00,NaN,NaN,NaN
25,US500,multi_source,bad,False,bad,1148,1148,2024-03-18 22:35:00+00:00,2025-12-16 19:18:00+00:00,2.000000,0.987430,0.585994
26,US500,multi_source,bad,True,bad,2,2,2025-04-06 22:02:00+00:00,2025-04-07 14:11:00+00:00,2.000000,0.353595,1.717520
27,US500,multi_source,good,False,good,288487,288487,2024-01-02 07:27:00+00:00,2025-12-12 07:04:00+00:00,2.000000,0.050000,0.736573
28,US500,multi_source,good,True,bad,9,9,2025-04-02 22:00:00+00:00,2025-06-22 22:00:00+00:00,2.000000,0.047346,1.383763
29,US500,multi_source,warning,False,warning,324216,324216,2024-01-01 23:00:00+00:00,2025-12-31 21:13:00+00:00,2.000000,0.199819,0.746665
30,US500,multi_source,warning,True,bad,22,22,2024-08-05 14:00:00+00:00,2025-05-11 22:00:00+00:00,2.000000,0.188305,3.094845
31,US500,single_source,warning,False,warning,75865,75865,2024-01-01 23:22:00+00:00,2025-12-31 21:59:00+00:00,1.000000,0.000000,0.720190
32,US500,single_source,warning,True,bad,3,3,2025-04-02 20:26:00+00:00,2025-10-12 22:00:00+00:00,1.000000,0.000000,1.822985
33,XAGUSD,missing,missing,False,missing,8585,0,2024-01-01 00:00:00+00:00,2025-12-31 23:59:00+00:00,NaN,NaN,NaN
34,XAGUSD,multi_source,bad,False,bad,930,930,2024-01-09 21:59:00+00:00,2025-12-31 05:34:00+00:00,2.820430,2.158656,0.804187
35,XAGUSD,multi_source,good,False,good,697722,697722,2024-01-01 23:04:00+00:00,2025-12-31 21:58:00+00:00,2.935493,0.050000,0.966708
36,XAGUSD,multi_source,good,True,bad,11,11,2024-02-02 13:30:00+00:00,2025-12-29 23:15:00+00:00,2.727273,0.042918,1.968936
37,XAGUSD,multi_source,warning,False,warning,11554,11554,2024-01-02 05:28:00+00:00,2025-12-31 21:57:00+00:00,2.945993,0.249995,0.994225
38,XAGUSD,multi_source,warning,True,bad,12,12,2024-06-12 12:30:00+00:00,2025-12-29 00:32:00+00:00,2.583333,0.212191,1.821065
39,XAGUSD,single_source,warning,False,warning,2922,2922,2024-01-01 23:01:00+00:00,2025-12-31 21:59:00+00:00,1.000000,0.000000,0.981501
40,XAGUSD,single_source,warning,True,bad,4,4,2025-04-02 22:02:00+00:00,2025-12-28 23:06:00+00:00,1.000000,0.000000,2.499984
41,XAUUSD,missing,missing,False,missing,8582,0,2024-01-01 00:00:00+00:00,2025-12-31 23:59:00+00:00,NaN,NaN,NaN
42,XAUUSD,multi_source,bad,False,bad,71,71,2024-01-08 05:34:00+00:00,2025-12-26 16:52:00+00:00,2.859155,0.550667,0.452501
43,XAUUSD,multi_source,bad,True,bad,2,2,2024-12-18 21:59:00+00:00,2025-05-11 22:00:00+00:00,2.000000,1.082971,1.091615
44,XAUUSD,multi_source,good,False,good,709020,709020,2024-01-01 23:01:00+00:00,2025-12-31 21:58:00+00:00,2.919641,0.049993,0.499533
45,XAUUSD,multi_source,good,True,bad,27,27,2024-01-05 13:30:00+00:00,2025-10-26 22:00:00+00:00,2.666667,0.041909,1.775922
46,XAUUSD,multi_source,warning,False,warning,1387,1387,2024-01-04 21:59:00+00:00,2025-12-31 05:34:00+00:00,2.894016,0.198607,0.372126
47,XAUUSD,multi_source,warning,True,bad,2,2,2024-11-25 03:28:00+00:00,2025-10-24 12:30:00+00:00,3.000000,0.126658,0.721068
48,XAUUSD,single_source,warning,False,warning,2649,2649,2024-01-01 23:00:00+00:00,2025-12-31 21:59:00+00:00,1.000000,0.000000,0.410392

In [10]:
method_1_generated_df = generate_candles_from_brokers(
    quality_wide_df,
    method=1,
)

method_1_silver_ohlcv_df = build_silver_ohlcv_from_generated(
    method_1_generated_df,
)

method_1_summary_df = build_silver_ohlcv_summary(
    method_1_silver_ohlcv_df,
)

method_1_summary_df

,asset,consensus_quality,candle_quality,is_outlier,quality_status,rows,generated_rows,start,end,avg_broker_count,max_close_diff_pct,max_abs_return_pct
0,BTCUSD,multi_source,bad,False,bad,229,229,2024-01-05 01:47:00+00:00,2025-10-10 23:16:00+00:00,2.000000,3.365631,1.887407
1,BTCUSD,multi_source,bad,True,bad,5,5,2024-01-05 01:48:00+00:00,2025-10-10 21:21:00+00:00,2.000000,5.355351,4.289804
2,BTCUSD,multi_source,good,False,good,981420,981420,2024-01-01 21:12:00+00:00,2025-12-31 14:58:00+00:00,2.000000,0.100000,1.815083
3,BTCUSD,multi_source,good,True,bad,5,5,2024-01-03 12:01:00+00:00,2025-01-23 20:12:00+00:00,2.000000,0.076114,2.908606
4,BTCUSD,multi_source,warning,False,warning,60188,60188,2024-01-02 00:15:00+00:00,2025-12-31 14:54:00+00:00,2.000000,0.299918,1.901710
5,BTCUSD,multi_source,warning,True,bad,3,3,2024-08-05 01:10:00+00:00,2024-12-05 22:28:00+00:00,2.000000,0.202889,3.675565
6,BTCUSD,single_source,warning,False,warning,10790,10790,2024-01-01 00:00:00+00:00,2025-12-31 23:59:00+00:00,1.000000,0.000000,1.303564
7,DAX,missing,missing,False,missing,21,0,2024-01-24 08:00:00+00:00,2025-10-02 07:01:00+00:00,NaN,NaN,NaN
8,DAX,multi_source,bad,False,bad,472,472,2024-03-21 08:00:00+00:00,2025-12-30 16:39:00+00:00,2.000000,1.543310,0.715070
9,DAX,multi_source,bad,True,bad,7,7,2024-08-05 07:06:00+00:00,2025-04-07 15:14:00+00:00,2.000000,2.614862,2.053114
10,DAX,multi_source,good,False,good,255398,255398,2024-01-02 08:02:00+00:00,2025-12-30 13:48:00+00:00,2.000000,0.049979,0.745232
11,DAX,multi_source,good,True,bad,7,7,2024-07-01 07:02:00+00:00,2025-06-27 07:00:00+00:00,2.000000,0.033537,1.358014
12,DAX,multi_source,warning,False,warning,2999,2999,2024-01-02 09:30:00+00:00,2025-12-30 14:47:00+00:00,2.000000,0.199071,0.733797
13,DAX,multi_source,warning,True,bad,4,4,2024-04-12 07:00:00+00:00,2025-04-09 11:02:00+00:00,2.000000,0.086112,1.309803
14,DAX,single_source,warning,False,warning,4673,4673,2024-01-02 08:00:00+00:00,2025-12-29 08:01:00+00:00,1.000000,0.000000,0.736429
15,DAX,single_source,warning,True,bad,59,59,2024-01-05 08:00:00+00:00,2025-11-21 08:00:00+00:00,1.000000,0.000000,8.029448
16,EURUSD,missing,missing,False,missing,18638,0,2024-01-01 19:00:00+00:00,2025-12-30 22:03:00+00:00,NaN,NaN,NaN
17,EURUSD,multi_source,bad,False,bad,3,3,2025-04-20 21:51:00+00:00,2025-04-20 21:59:00+00:00,2.000000,0.124046,0.104650
18,EURUSD,multi_source,good,False,good,706079,706079,2024-01-01 22:00:00+00:00,2025-12-31 16:59:00+00:00,2.925188,0.019979,0.198161
19,EURUSD,multi_source,good,True,bad,79,79,2024-01-05 13:30:00+00:00,2025-10-24 12:30:00+00:00,2.924051,0.016411,0.573896
20,EURUSD,multi_source,warning,False,warning,596,596,2024-01-05 13:39:00+00:00,2025-12-28 22:20:00+00:00,2.558725,0.080412,0.193261
21,EURUSD,multi_source,warning,True,bad,9,9,2025-01-20 13:30:00+00:00,2025-10-29 18:35:00+00:00,3.000000,0.068605,0.695718
22,EURUSD,single_source,warning,False,warning,13583,13583,2024-01-01 19:01:00+00:00,2025-12-30 22:14:00+00:00,1.000000,0.000000,0.198483
23,EURUSD,single_source,warning,True,bad,3,3,2025-02-02 19:24:00+00:00,2025-02-02 19:29:00+00:00,1.000000,0.000000,0.364183
24,US500,missing,missing,False,missing,3218,0,2024-02-01 00:59:00+00:00,2025-12-31 23:59:00+00:00,NaN,NaN,NaN
25,US500,multi_source,bad,False,bad,1146,1146,2024-03-18 22:35:00+00:00,2025-12-16 19:18:00+00:00,2.000000,0.987430,0.689219
26,US500,multi_source,bad,True,bad,4,4,2024-04-10 12:30:00+00:00,2025-04-23 13:37:00+00:00,2.000000,0.903889,1.804556
27,US500,multi_source,good,False,good,288487,288487,2024-01-02 07:27:00+00:00,2025-12-12 07:04:00+00:00,2.000000,0.050000,0.732639
28,US500,multi_source,good,True,bad,9,9,2025-04-02 22:00:00+00:00,2025-06-22 22:00:00+00:00,2.000000,0.047346,1.447062
29,US500,multi_source,warning,False,warning,324215,324215,2024-01-01 23:00:00+00:00,2025-12-31 21:13:00+00:00,2.000000,0.199819,0.739082
30,US500,multi_source,warning,True,bad,23,23,2024-08-05 14:00:00+00:00,2025-05-11 22:00:00+00:00,2.000000,0.188305,3.175012
31,US500,single_source,warning,False,warning,75865,75865,2024-01-01 23:22:00+00:00,2025-12-31 21:59:00+00:00,1.000000,0.000000,0.720190
32,US500,single_source,warning,True,bad,3,3,2025-04-02 20:26:00+00:00,2025-10-12 22:00:00+00:00,1.000000,0.000000,1.822985
33,XAGUSD,missing,missing,False,missing,8585,0,2024-01-01 00:00:00+00:00,2025-12-31 23:59:00+00:00,NaN,NaN,NaN
34,XAGUSD,multi_source,bad,False,bad,927,927,2024-01-09 21:59:00+00:00,2025-12-31 05:34:00+00:00,2.823085,2.158656,0.995797
35,XAGUSD,multi_source,bad,True,bad,3,3,2025-04-06 22:07:00+00:00,2025-10-14 05:58:00+00:00,2.000000,1.369503,1.131820
36,XAGUSD,multi_source,good,False,good,697722,697722,2024-01-01 23:04:00+00:00,2025-12-31 21:58:00+00:00,2.935493,0.050000,0.978023
37,XAGUSD,multi_source,good,True,bad,11,11,2024-02-02 13:30:00+00:00,2025-12-29 23:15:00+00:00,2.727273,0.042918,1.963342
38,XAGUSD,multi_source,warning,False,warning,11553,11553,2024-01-02 05:28:00+00:00,2025-12-31 21:57:00+00:00,2.945988,0.249995,0.981169
39,XAGUSD,multi_source,warning,True,bad,13,13,2024-06-12 12:30:00+00:00,2025-12-29 01:00:00+00:00,2.615385,0.212191,1.852175
40,XAGUSD,single_source,warning,False,warning,2921,2921,2024-01-01 23:01:00+00:00,2025-12-31 21:59:00+00:00,1.000000,0.000000,0.981501
41,XAGUSD,single_source,warning,True,bad,5,5,2025-04-02 22:02:00+00:00,2025-12-28 23:06:00+00:00,1.000000,0.000000,2.477971
42,XAUUSD,missing,missing,False,missing,8582,0,2024-01-01 00:00:00+00:00,2025-12-31 23:59:00+00:00,NaN,NaN,NaN
43,XAUUSD,multi_source,bad,False,bad,69,69,2024-01-08 05:34:00+00:00,2025-12-26 16:52:00+00:00,2.840580,1.082971,0.308436
44,XAUUSD,multi_source,bad,True,bad,4,4,2025-04-24 22:14:00+00:00,2025-11-16 23:06:00+00:00,2.750000,0.875892,1.517337
45,XAUUSD,multi_source,good,False,good,709018,709018,2024-01-01 23:01:00+00:00,2025-12-31 21:58:00+00:00,2.919640,0.049993,0.493778
46,XAUUSD,multi_source,good,True,bad,29,29,2024-01-05 13:30:00+00:00,2025-10-26 22:00:00+00:00,2.724138,0.041909,1.777200
47,XAUUSD,multi_source,warning,False,warning,1385,1385,2024-01-04 21:59:00+00:00,2025-12-31 05:34:00+00:00,2.893863,0.198607,0.384394
48,XAUUSD,multi_source,warning,True,bad,4,4,2024-11-25 03:28:00+00:00,2025-10-24 12:30:00+00:00,3.000000,0.126658,0.595700
49,XAUUSD,single_source,warning,False,warning,2648,2648,2024-01-01 23:00:00+00:00,2025-12-31 21:59:00+00:00,1.000000,0.000000,0.410392
50,XAUUSD,single_source,warning,True,bad,1,1,2025-11-28 08:05:00+00:00,2025-11-28 08:05:00+00:00,1.000000,0.000000,0.573229

In [11]:
import quality.broker_ranking

importlib.reload(quality.broker_ranking)

from quality.broker_ranking import build_broker_ranking


method_0_broker_ranking_df = build_broker_ranking(
    method_0_generated_df,
)

method_1_broker_ranking_df = build_broker_ranking(
    method_1_generated_df,
)

method_0_broker_ranking_df

,asset,broker,calendar_rows,broker_rows,missing_rows,coverage_ratio,mean_abs_diff,median_abs_diff,max_abs_diff,mean_abs_diff_pct,median_abs_diff_pct,max_abs_diff_pct
0,BTCUSD,binance,1052640,1052640,0,1.000000,15.192886,10.23500,2784.120000,0.017654,0.012858,2.607846
1,BTCUSD,dukascopy,1052640,1041850,10790,0.989750,15.350232,10.40000,2784.120000,0.017837,0.013055,2.607846
2,DAX,interactive_brokers,263640,262879,761,0.997113,1.138452,0.77950,242.183250,0.005446,0.003789,1.290558
3,DAX,dukascopy,263640,259627,4013,0.984778,1.152712,0.79175,242.183250,0.005515,0.003848,1.290558
4,EURUSD,saxo_bank,738990,716928,22062,0.970146,0.000017,0.00001,0.000785,0.001547,0.000970,0.067273
5,EURUSD,dukascopy,738990,701686,37304,0.949520,0.000004,0.00000,0.000708,0.000333,0.000000,0.061985
6,EURUSD,interactive_brokers,738990,662175,76815,0.896054,0.000003,0.00000,0.000485,0.000311,0.000000,0.043316
7,US500,interactive_brokers,692970,652337,40633,0.941364,1.549878,1.42225,32.379750,0.026365,0.024930,0.491289
8,US500,dukascopy,692970,651299,41671,0.939866,1.552348,1.42425,32.379750,0.026407,0.024974,0.491289
9,XAGUSD,saxo_bank,721740,707767,13973,0.980640,0.001548,0.00060,0.404000,0.004336,0.001953,0.747817
10,XAGUSD,dukascopy,721740,707619,14121,0.980435,0.002467,0.00170,0.675250,0.007622,0.005105,1.372494
11,XAGUSD,interactive_brokers,721740,672420,49320,0.931665,0.001468,0.00025,1.509500,0.003808,0.000784,2.048377
12,XAUUSD,saxo_bank,721740,709472,12268,0.983002,0.061720,0.03500,17.375000,0.002006,0.001264,0.518422
13,XAUUSD,dukascopy,721740,695140,26600,0.963145,0.020733,0.00500,14.666500,0.000692,0.000230,0.538569
14,XAUUSD,interactive_brokers,721740,672420,49320,0.931665,0.029757,0.00500,14.337500,0.000972,0.000208,0.538569

In [12]:
import importlib

import pipelines.silver_generated_ohlcv_runner

importlib.reload(pipelines.silver_generated_ohlcv_runner)

from pipelines.silver_generated_ohlcv_runner import (
    upload_silver_generated_ohlcv_with_preview,
)


silver_methods = [
    {
        "generation_method_id": 0,
        "generation_method": "median_ohlc",
        "silver_ohlcv_df": method_0_silver_ohlcv_df,
    },
    {
        "generation_method_id": 1,
        "generation_method": "preferred_broker_ohlc",
        "silver_ohlcv_df": method_1_silver_ohlcv_df,
    },
]

silver_upload_results = {}

for method_config in silver_methods:
    method_id = method_config["generation_method_id"]
    method_name = method_config["generation_method"]

    print(f"Uploading silver method {method_id}: {method_name}")

    silver_upload_results[method_id] = upload_silver_generated_ohlcv_with_preview(
        silver_ohlcv_df=method_config["silver_ohlcv_df"],
        interval=INTERVAL,
        generation_method_id=method_id,
        generation_method=method_name,
        overwrite=True,
        print_progress=True,
    )

silver_upload_results[0]["upload_results"], silver_upload_results[1]["upload_results"]

Uploading silver method 0: median_ohlc
Uploading silver generated OHLCV: BTCUSD 2024-01
Uploading silver generated OHLCV: DAX 2024-01
Uploading silver generated OHLCV: EURUSD 2024-01
Uploading silver generated OHLCV: US500 2024-01
Uploading silver generated OHLCV: XAGUSD 2024-01
Uploading silver generated OHLCV: XAUUSD 2024-01
Uploading silver generated OHLCV: BTCUSD 2024-02
Uploading silver generated OHLCV: DAX 2024-02
Uploading silver generated OHLCV: EURUSD 2024-02
Uploading silver generated OHLCV: US500 2024-02
Uploading silver generated OHLCV: XAGUSD 2024-02
Uploading silver generated OHLCV: XAUUSD 2024-02
Uploading silver generated OHLCV: BTCUSD 2024-03
Uploading silver generated OHLCV: DAX 2024-03
Uploading silver generated OHLCV: EURUSD 2024-03
Uploading silver generated OHLCV: US500 2024-03
Uploading silver generated OHLCV: XAGUSD 2024-03
Uploading silver generated OHLCV: XAUUSD 2024-03
Uploading silver generated OHLCV: BTCUSD 2024-04
Uploading silver generated OHLCV: DAX 2024-04
Uploading silver generated OHLCV: EURUSD 2024-04
Uploading silver generated OHLCV: US500 2024-04
Uploading silver generated OHLCV: XAGUSD 2024-04
Uploading silver generated OHLCV: XAUUSD 2024-04
Uploading silver generated OHLCV: BTCUSD 2024-05
Uploading silver generated OHLCV: DAX 2024-05
Uploading silver generated OHLCV: EURUSD 2024-05
Uploading silver generated OHLCV: US500 2024-05
Uploading silver generated OHLCV: XAGUSD 2024-05
Uploading silver generated OHLCV: XAUUSD 2024-05
Uploading silver generated OHLCV: BTCUSD 2024-06
Uploading silver generated OHLCV: DAX 2024-06
Uploading silver generated OHLCV: EURUSD 2024-06
Uploading silver generated OHLCV: US500 2024-06
Uploading silver generated OHLCV: XAGUSD 2024-06
Uploading silver generated OHLCV: XAUUSD 2024-06
Uploading silver generated OHLCV: BTCUSD 2024-07
Uploading silver generated OHLCV: DAX 2024-07
Uploading silver generated OHLCV: EURUSD 2024-07
Uploading silver generated OHLCV: US500 2024-07
Uploading silver generated OHLCV: XAGUSD 2024-07
Uploading silver generated OHLCV: XAUUSD 2024-07
Uploading silver generated OHLCV: BTCUSD 2024-08
Uploading silver generated OHLCV: DAX 2024-08
Uploading silver generated OHLCV: EURUSD 2024-08
Uploading silver generated OHLCV: US500 2024-08
Uploading silver generated OHLCV: XAGUSD 2024-08
Uploading silver generated OHLCV: XAUUSD 2024-08
Uploading silver generated OHLCV: BTCUSD 2024-09
Uploading silver generated OHLCV: DAX 2024-09
Uploading silver generated OHLCV: EURUSD 2024-09
Uploading silver generated OHLCV: US500 2024-09
Uploading silver generated OHLCV: XAGUSD 2024-09
Uploading silver generated OHLCV: XAUUSD 2024-09
Uploading silver generated OHLCV: BTCUSD 2024-10
Uploading silver generated OHLCV: DAX 2024-10
Uploading silver generated OHLCV: EURUSD 2024-10
Uploading silver generated OHLCV: US500 2024-10
Uploading silver generated OHLCV: XAGUSD 2024-10
Uploading silver generated OHLCV: XAUUSD 2024-10
Uploading silver generated OHLCV: BTCUSD 2024-11
Uploading silver generated OHLCV: DAX 2024-11
Uploading silver generated OHLCV: EURUSD 2024-11
Uploading silver generated OHLCV: US500 2024-11
Uploading silver generated OHLCV: XAGUSD 2024-11
Uploading silver generated OHLCV: XAUUSD 2024-11
Uploading silver generated OHLCV: BTCUSD 2024-12
Uploading silver generated OHLCV: DAX 2024-12
Uploading silver generated OHLCV: EURUSD 2024-12
Uploading silver generated OHLCV: US500 2024-12
Uploading silver generated OHLCV: XAGUSD 2024-12
Uploading silver generated OHLCV: XAUUSD 2024-12
Uploading silver generated OHLCV: BTCUSD 2025-01
Uploading silver generated OHLCV: DAX 2025-01
Uploading silver generated OHLCV: EURUSD 2025-01
Uploading silver generated OHLCV: US500 2025-01
Uploading silver generated OHLCV: XAGUSD 2025-01
Uploading silver generated OHLCV: XAUUSD 2025-01
Uploading silver generated OHLCV: BTCUSD 2025-02
Uploading silver generated OHLCV: DAX 2025-02
Uploading silver generated OHLCV: EURUSD 2025-02
Uploading silver generated OHLCV: US500 2025-02
Uploading silver generated OHLCV: XAGUSD 2025-02
Uploading silver generated OHLCV: XAUUSD 2025-02
Uploading silver generated OHLCV: BTCUSD 2025-03
Uploading silver generated OHLCV: DAX 2025-03
Uploading silver generated OHLCV: EURUSD 2025-03
Uploading silver generated OHLCV: US500 2025-03
Uploading silver generated OHLCV: XAGUSD 2025-03
Uploading silver generated OHLCV: XAUUSD 2025-03
Uploading silver generated OHLCV: BTCUSD 2025-04
Uploading silver generated OHLCV: DAX 2025-04
Uploading silver generated OHLCV: EURUSD 2025-04
Uploading silver generated OHLCV: US500 2025-04
Uploading silver generated OHLCV: XAGUSD 2025-04
Uploading silver generated OHLCV: XAUUSD 2025-04
Uploading silver generated OHLCV: BTCUSD 2025-05
Uploading silver generated OHLCV: DAX 2025-05
Uploading silver generated OHLCV: EURUSD 2025-05
Uploading silver generated OHLCV: US500 2025-05
Uploading silver generated OHLCV: XAGUSD 2025-05
Uploading silver generated OHLCV: XAUUSD 2025-05
Uploading silver generated OHLCV: BTCUSD 2025-06
Uploading silver generated OHLCV: DAX 2025-06
Uploading silver generated OHLCV: EURUSD 2025-06
Uploading silver generated OHLCV: US500 2025-06
Uploading silver generated OHLCV: XAGUSD 2025-06
Uploading silver generated OHLCV: XAUUSD 2025-06
Uploading silver generated OHLCV: BTCUSD 2025-07
Uploading silver generated OHLCV: DAX 2025-07
Uploading silver generated OHLCV: EURUSD 2025-07
Uploading silver generated OHLCV: US500 2025-07
Uploading silver generated OHLCV: XAGUSD 2025-07
Uploading silver generated OHLCV: XAUUSD 2025-07
Uploading silver generated OHLCV: BTCUSD 2025-08
Uploading silver generated OHLCV: DAX 2025-08
Uploading silver generated OHLCV: EURUSD 2025-08
Uploading silver generated OHLCV: US500 2025-08
Uploading silver generated OHLCV: XAGUSD 2025-08
Uploading silver generated OHLCV: XAUUSD 2025-08
Uploading silver generated OHLCV: BTCUSD 2025-09
Uploading silver generated OHLCV: DAX 2025-09
Uploading silver generated OHLCV: EURUSD 2025-09
Uploading silver generated OHLCV: US500 2025-09
Uploading silver generated OHLCV: XAGUSD 2025-09
Uploading silver generated OHLCV: XAUUSD 2025-09
Uploading silver generated OHLCV: BTCUSD 2025-10
Uploading silver generated OHLCV: DAX 2025-10
Uploading silver generated OHLCV: EURUSD 2025-10
Uploading silver generated OHLCV: US500 2025-10
Uploading silver generated OHLCV: XAGUSD 2025-10
Uploading silver generated OHLCV: XAUUSD 2025-10
Uploading silver generated OHLCV: BTCUSD 2025-11
Uploading silver generated OHLCV: DAX 2025-11
Uploading silver generated OHLCV: EURUSD 2025-11
Uploading silver generated OHLCV: US500 2025-11
Uploading silver generated OHLCV: XAGUSD 2025-11
Uploading silver generated OHLCV: XAUUSD 2025-11
Uploading silver generated OHLCV: BTCUSD 2025-12
Uploading silver generated OHLCV: DAX 2025-12
Uploading silver generated OHLCV: EURUSD 2025-12
Uploading silver generated OHLCV: US500 2025-12
Uploading silver generated OHLCV: XAGUSD 2025-12
Uploading silver generated OHLCV: XAUUSD 2025-12
Uploading silver method 1: preferred_broker_ohlc
Uploading silver generated OHLCV: BTCUSD 2024-01
Uploading silver generated OHLCV: DAX 2024-01
Uploading silver generated OHLCV: EURUSD 2024-01
Uploading silver generated OHLCV: US500 2024-01
Uploading silver generated OHLCV: XAGUSD 2024-01
Uploading silver generated OHLCV: XAUUSD 2024-01
Uploading silver generated OHLCV: BTCUSD 2024-02
Uploading silver generated OHLCV: DAX 2024-02
Uploading silver generated OHLCV: EURUSD 2024-02
Uploading silver generated OHLCV: US500 2024-02
Uploading silver generated OHLCV: XAGUSD 2024-02
Uploading silver generated OHLCV: XAUUSD 2024-02
Uploading silver generated OHLCV: BTCUSD 2024-03
Uploading silver generated OHLCV: DAX 2024-03
Uploading silver generated OHLCV: EURUSD 2024-03
Uploading silver generated OHLCV: US500 2024-03
Uploading silver generated OHLCV: XAGUSD 2024-03
Uploading silver generated OHLCV: XAUUSD 2024-03
Uploading silver generated OHLCV: BTCUSD 2024-04
Uploading silver generated OHLCV: DAX 2024-04
Uploading silver generated OHLCV: EURUSD 2024-04
Uploading silver generated OHLCV: US500 2024-04
Uploading silver generated OHLCV: XAGUSD 2024-04
Uploading silver generated OHLCV: XAUUSD 2024-04
Uploading silver generated OHLCV: BTCUSD 2024-05
Uploading silver generated OHLCV: DAX 2024-05
Uploading silver generated OHLCV: EURUSD 2024-05
Uploading silver generated OHLCV: US500 2024-05
Uploading silver generated OHLCV: XAGUSD 2024-05
Uploading silver generated OHLCV: XAUUSD 2024-05
Uploading silver generated OHLCV: BTCUSD 2024-06
Uploading silver generated OHLCV: DAX 2024-06
Uploading silver generated OHLCV: EURUSD 2024-06
Uploading silver generated OHLCV: US500 2024-06
Uploading silver generated OHLCV: XAGUSD 2024-06
Uploading silver generated OHLCV: XAUUSD 2024-06
Uploading silver generated OHLCV: BTCUSD 2024-07
Uploading silver generated OHLCV: DAX 2024-07
Uploading silver generated OHLCV: EURUSD 2024-07
Uploading silver generated OHLCV: US500 2024-07
Uploading silver generated OHLCV: XAGUSD 2024-07
Uploading silver generated OHLCV: XAUUSD 2024-07
Uploading silver generated OHLCV: BTCUSD 2024-08
Uploading silver generated OHLCV: DAX 2024-08
Uploading silver generated OHLCV: EURUSD 2024-08
Uploading silver generated OHLCV: US500 2024-08
Uploading silver generated OHLCV: XAGUSD 2024-08
Uploading silver generated OHLCV: XAUUSD 2024-08
Uploading silver generated OHLCV: BTCUSD 2024-09
Uploading silver generated OHLCV: DAX 2024-09
Uploading silver generated OHLCV: EURUSD 2024-09
Uploading silver generated OHLCV: US500 2024-09
Uploading silver generated OHLCV: XAGUSD 2024-09
Uploading silver generated OHLCV: XAUUSD 2024-09
Uploading silver generated OHLCV: BTCUSD 2024-10
Uploading silver generated OHLCV: DAX 2024-10
Uploading silver generated OHLCV: EURUSD 2024-10
Uploading silver generated OHLCV: US500 2024-10
Uploading silver generated OHLCV: XAGUSD 2024-10
Uploading silver generated OHLCV: XAUUSD 2024-10
Uploading silver generated OHLCV: BTCUSD 2024-11
Uploading silver generated OHLCV: DAX 2024-11
Uploading silver generated OHLCV: EURUSD 2024-11
Uploading silver generated OHLCV: US500 2024-11
Uploading silver generated OHLCV: XAGUSD 2024-11
Uploading silver generated OHLCV: XAUUSD 2024-11
Uploading silver generated OHLCV: BTCUSD 2024-12
Uploading silver generated OHLCV: DAX 2024-12
Uploading silver generated OHLCV: EURUSD 2024-12
Uploading silver generated OHLCV: US500 2024-12
Uploading silver generated OHLCV: XAGUSD 2024-12
Uploading silver generated OHLCV: XAUUSD 2024-12
Uploading silver generated OHLCV: BTCUSD 2025-01
Uploading silver generated OHLCV: DAX 2025-01
Uploading silver generated OHLCV: EURUSD 2025-01
Uploading silver generated OHLCV: US500 2025-01
Uploading silver generated OHLCV: XAGUSD 2025-01
Uploading silver generated OHLCV: XAUUSD 2025-01
Uploading silver generated OHLCV: BTCUSD 2025-02
Uploading silver generated OHLCV: DAX 2025-02
Uploading silver generated OHLCV: EURUSD 2025-02
Uploading silver generated OHLCV: US500 2025-02
Uploading silver generated OHLCV: XAGUSD 2025-02
Uploading silver generated OHLCV: XAUUSD 2025-02
Uploading silver generated OHLCV: BTCUSD 2025-03
Uploading silver generated OHLCV: DAX 2025-03
Uploading silver generated OHLCV: EURUSD 2025-03
Uploading silver generated OHLCV: US500 2025-03
Uploading silver generated OHLCV: XAGUSD 2025-03
Uploading silver generated OHLCV: XAUUSD 2025-03
Uploading silver generated OHLCV: BTCUSD 2025-04
Uploading silver generated OHLCV: DAX 2025-04
Uploading silver generated OHLCV: EURUSD 2025-04
Uploading silver generated OHLCV: US500 2025-04
Uploading silver generated OHLCV: XAGUSD 2025-04
Uploading silver generated OHLCV: XAUUSD 2025-04
Uploading silver generated OHLCV: BTCUSD 2025-05
Uploading silver generated OHLCV: DAX 2025-05
Uploading silver generated OHLCV: EURUSD 2025-05
Uploading silver generated OHLCV: US500 2025-05
Uploading silver generated OHLCV: XAGUSD 2025-05
Uploading silver generated OHLCV: XAUUSD 2025-05
Uploading silver generated OHLCV: BTCUSD 2025-06
Uploading silver generated OHLCV: DAX 2025-06
Uploading silver generated OHLCV: EURUSD 2025-06
Uploading silver generated OHLCV: US500 2025-06
Uploading silver generated OHLCV: XAGUSD 2025-06
Uploading silver generated OHLCV: XAUUSD 2025-06
Uploading silver generated OHLCV: BTCUSD 2025-07
Uploading silver generated OHLCV: DAX 2025-07
Uploading silver generated OHLCV: EURUSD 2025-07
Uploading silver generated OHLCV: US500 2025-07
Uploading silver generated OHLCV: XAGUSD 2025-07
Uploading silver generated OHLCV: XAUUSD 2025-07
Uploading silver generated OHLCV: BTCUSD 2025-08
Uploading silver generated OHLCV: DAX 2025-08
Uploading silver generated OHLCV: EURUSD 2025-08
Uploading silver generated OHLCV: US500 2025-08
Uploading silver generated OHLCV: XAGUSD 2025-08
Uploading silver generated OHLCV: XAUUSD 2025-08
Uploading silver generated OHLCV: BTCUSD 2025-09
Uploading silver generated OHLCV: DAX 2025-09
Uploading silver generated OHLCV: EURUSD 2025-09
Uploading silver generated OHLCV: US500 2025-09
Uploading silver generated OHLCV: XAGUSD 2025-09
Uploading silver generated OHLCV: XAUUSD 2025-09
Uploading silver generated OHLCV: BTCUSD 2025-10
Uploading silver generated OHLCV: DAX 2025-10
Uploading silver generated OHLCV: EURUSD 2025-10
Uploading silver generated OHLCV: US500 2025-10
Uploading silver generated OHLCV: XAGUSD 2025-10
Uploading silver generated OHLCV: XAUUSD 2025-10
Uploading silver generated OHLCV: BTCUSD 2025-11
Uploading silver generated OHLCV: DAX 2025-11
Uploading silver generated OHLCV: EURUSD 2025-11
Uploading silver generated OHLCV: US500 2025-11
Uploading silver generated OHLCV: XAGUSD 2025-11
Uploading silver generated OHLCV: XAUUSD 2025-11
Uploading silver generated OHLCV: BTCUSD 2025-12
Uploading silver generated OHLCV: DAX 2025-12
Uploading silver generated OHLCV: EURUSD 2025-12
Uploading silver generated OHLCV: US500 2025-12
Uploading silver generated OHLCV: XAGUSD 2025-12
Uploading silver generated OHLCV: XAUUSD 2025-12

(       status   asset  year  month  \
 0    uploaded  BTCUSD  2024      1
 1    uploaded     DAX  2024      1
 2    uploaded  EURUSD  2024      1
 3    uploaded   US500  2024      1
 4    uploaded  XAGUSD  2024      1
 ..        ...     ...   ...    ...
 139  uploaded     DAX  2025     12
 140  uploaded  EURUSD  2025     12
 141  uploaded   US500  2025     12
 142  uploaded  XAGUSD  2025     12
 143  uploaded  XAUUSD  2025     12

                                            message  row_count
 0    Silver generated OHLCV uploaded successfully.      44640
 1    Silver generated OHLCV uploaded successfully.      11440
 2    Silver generated OHLCV uploaded successfully.      31650
 3    Silver generated OHLCV uploaded successfully.      29040
 4    Silver generated OHLCV uploaded successfully.      31740
 ..                                             ...        ...
 139  Silver generated OHLCV uploaded successfully.       9880
 140  Silver generated OHLCV uploaded successfully.      30840
 141  Silver generated OHLCV uploaded successfully.      30135
 142  Silver generated OHLCV uploaded successfully.      31740
 143  Silver generated OHLCV uploaded successfully.      31740

 [144 rows x 6 columns],
        status   asset  year  month  \
 0    uploaded  BTCUSD  2024      1
 1    uploaded     DAX  2024      1
 2    uploaded  EURUSD  2024      1
 3    uploaded   US500  2024      1
 4    uploaded  XAGUSD  2024      1
 ..        ...     ...   ...    ...
 139  uploaded     DAX  2025     12
 140  uploaded  EURUSD  2025     12
 141  uploaded   US500  2025     12
 142  uploaded  XAGUSD  2025     12
 143  uploaded  XAUUSD  2025     12

                                            message  row_count
 0    Silver generated OHLCV uploaded successfully.      44640
 1    Silver generated OHLCV uploaded successfully.      11440
 2    Silver generated OHLCV uploaded successfully.      31650
 3    Silver generated OHLCV uploaded successfully.      29040
 4    Silver generated OHLCV uploaded successfully.      31740
 ..                                             ...        ...
 139  Silver generated OHLCV uploaded successfully.       9880
 140  Silver generated OHLCV uploaded successfully.      30840
 141  Silver generated OHLCV uploaded successfully.      30135
 142  Silver generated OHLCV uploaded successfully.      31740
 143  Silver generated OHLCV uploaded successfully.      31740

 [144 rows x 6 columns])